### ISSUE TITLE
Создать nx-monorepo

### ISSUE THREAD

**Issue by podkovyrovda** [Horizontal-Bar/hoba#1]
### Technical Info

apps/hoba-web

- [x] node 14.17
- [x] angular 12
- [x] taiga-ui @latest
- [x] ionic 6
- [x] @ngrx/store

apps/hoba-api
- [x] nestjs @latest

apps/hoba-ws
- [x] nestjs @latest 
- [x] socket.io [docs](https://docs.nestjs.com/websockets/gateways)

- [x] libs/shared/api-interfaces
- [x] libs/hoba-web/... lazy-routes ... features
- [x] libs/hoba-api/... controllers services ...
- [x] libs/hoba-ws/... controllers services ...

### Acceptance Criteria

- [x] все приложения стартуют

**Comment by PavelMinev** [comment]
Process is in progress!!!
